<?php

declare(strict_types=1);

namespace IReserve\Reports;

use InvalidArgumentException;
use Paperdoc\Document\Style\{PageSetup, ParagraphStyle, RunningElement, TableStyle, TextStyle};
use Paperdoc\Document\{Image, Paragraph, Section, Table, TableCell, TableRow, TextRun};
use Paperdoc\Enum\{Alignment, PageSize};
use Paperdoc\Support\DocumentManager;

final class ReportGenerator
{
    private const FORMATS = ['pdf', 'xlsx', 'csv'];

    private const CONTENT_TYPES = [
        'pdf' => 'application/pdf',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'csv' => 'text/csv; charset=utf-8',
    ];

    /**
     * @param array<string, mixed> $payload
     * @return array{content: string, contentType: string, filename: string}
     */
    public function generate(array $payload): array
    {
        $format = strtolower((string) ($payload['format'] ?? ''));
        $title = trim((string) ($payload['title'] ?? ''));
        $reportType = trim((string) ($payload['reportType'] ?? 'report'));
        $columns = $payload['columns'] ?? [];
        $rows = $payload['rows'] ?? [];

        if (! in_array($format, self::FORMATS, true)) {
            throw new InvalidArgumentException('Invalid export format.');
        }
        if ($title === '' || ! is_array($columns) || $columns === []) {
            throw new InvalidArgumentException('Invalid report definition.');
        }
        if (! is_array($rows) || $rows === []) {
            throw new InvalidArgumentException('No data found for the selected filters.');
        }

        $document = $format === 'csv'
            ? $this->buildCsvDocument($payload)
            : $this->buildProfessionalDocument($payload, $format);
        $content = DocumentManager::renderAs($document, $format);
        if ($content === '') {
            throw new \RuntimeException('Paperdoc returned an empty document.');
        }

        $date = substr((string) ($payload['generatedAt'] ?? date(DATE_ATOM)), 0, 10);
        $filename = preg_replace('/[^a-z0-9-]+/', '-', strtolower(str_replace('_', '-', $reportType)));
        $filename = trim((string) $filename, '-') ?: 'report';

        return [
            'content' => $content,
            'contentType' => self::CONTENT_TYPES[$format],
            'filename' => "{$filename}-{$date}.{$format}",
        ];
    }

    /**
     * CSV intentionally contains only headers and filtered data rows.
     *
     * @param array<string, mixed> $payload
     */
    private function buildCsvDocument(array $payload): object
    {
        $document = DocumentManager::create('csv', (string) $payload['title']);
        $section = Section::make('Data');
        $section->addElement($this->dataTable($payload, false));
        $document->addSection($section);

        return $document;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function buildProfessionalDocument(array $payload, string $format): object
    {
        if ($format === 'pdf' && is_array($payload['documentModel'] ?? null)) {
            return $this->buildModelDocument($payload);
        }

        $presentation = $this->presentation($payload);
        $theme = $this->theme($presentation['headerTheme']);
        $baseSize = (float) $presentation['baseFontSize'];
        $document = DocumentManager::create($format, (string) $payload['title']);
        $document->setDefaultTextStyle(
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setFontSize($baseSize)
                ->setColor('#24332C')
        );

        if ($format === 'pdf') {
            $document->setHeader(
                RunningElement::make('iReserve | {title}')
                    ->setAlignment(Alignment::LEFT)
                    ->setStyle(
                        TextStyle::make()
                            ->setFontFamily($presentation['fontFamily'])
                            ->setFontSize(max(7, $baseSize - 3))
                            ->setBold()
                            ->setColor($theme['accent'])
                    )
            );
            $document->setFooter(
                RunningElement::make('Generated by iReserve Smart Village Reservation System | Page {page} of {pages}')
                    ->setAlignment(Alignment::CENTER)
                    ->setStyle(
                        TextStyle::make()
                            ->setFontFamily($presentation['fontFamily'])
                            ->setFontSize(max(7, $baseSize - 3.5))
                            ->setColor('#66756E')
                    )
            );
        }

        $section = Section::make($this->sheetName((string) $payload['title']));
        if ($format === 'pdf') {
            $orientation = $presentation['orientation'] === PageSetup::ORIENTATION_LANDSCAPE
                ? PageSetup::ORIENTATION_LANDSCAPE
                : PageSetup::ORIENTATION_PORTRAIT;
            $padding = match ($presentation['spacing']) {
                'compact' => [28, 26, 34, 26],
                'comfortable' => [46, 42, 50, 42],
                default => [38, 34, 42, 34],
            };
            $pageSetup = PageSetup::fromSize($this->pageSize($presentation['paperSize']), $orientation)
                ->setPadding(...$padding)
                ->setBackgroundColor('#FFFFFF');
            $watermarkData = base64_decode((string) ($payload['watermarkData'] ?? ''), true);
            if (is_string($watermarkData) && $watermarkData !== '') {
                $pageSetup
                    ->setBackgroundImage(Image::fromData($watermarkData, 'image/png', 420, 260, 'iReserve watermark'))
                    ->setBackgroundSize(PageSetup::BG_SIZE_AUTO)
                    ->setBackgroundPosition('center center')
                    ->setBackgroundRepeat('no-repeat');
            }
            $section->setPageSetup($pageSetup);
        }

        $section->addParagraph(
            'iReserve Smart Village Reservation System',
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setBold()
                ->setFontSize(max(9, $baseSize - 1))
                ->setColor($theme['accent'])
        );
        $section->addParagraph(
            (string) $payload['title'],
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setFontSize($baseSize + 9)
                ->setBold()
                ->setColor('#17211D')
        );
        $section->addParagraph(
            (string) ($payload['subtitle'] ?? ''),
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setFontSize(max(7, $baseSize - 3))
                ->setColor('#66756E')
        );
        $section->addRule()->setColor($theme['softBorder'])->setThickness(1.0);

        $section->addElement($this->metadataTable($payload, $presentation));
        $section->addParagraph(
            'Applied Filters',
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setFontSize($baseSize + 1)
                ->setBold()
                ->setColor('#17211D')
        );
        $section->addParagraph(
            $this->filtersText($payload['filters'] ?? []),
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setFontSize(max(7, $baseSize - 4))
                ->setColor('#31463D')
        );

        $summary = $payload['summary'] ?? [];
        if (is_array($summary) && $summary !== []) {
            $section->addParagraph(
                'Summary',
                TextStyle::make()
                    ->setFontFamily($presentation['fontFamily'])
                    ->setFontSize($baseSize + 1)
                    ->setBold()
                    ->setColor('#17211D')
            );
            $section->addElement($this->summaryTable($summary, $presentation));
        }

        $section->addParagraph(
            'Report Details',
            TextStyle::make()
                ->setFontFamily($presentation['fontFamily'])
                ->setFontSize($baseSize + 1)
                ->setBold()
                ->setColor('#17211D')
        );
        $section->addElement($this->dataTable($payload, $format === 'pdf'));
        $document->addSection($section);

        return $document;
    }

    /**
     * Render the shared frontend/backend report document model.
     *
     * @param array<string, mixed> $payload
     */
    private function buildModelDocument(array $payload): object
    {
        $model = $payload['documentModel'];
        $page = $model['page'];
        $typography = $model['typography'];
        $theme = $model['theme'];
        $document = DocumentManager::create('pdf', (string) $model['title']);
        $document->setDefaultTextStyle(
            TextStyle::make()
                ->setFontFamily((string) $typography['fontFamily'])
                ->setFontSize((float) $typography['baseFontSize'])
                ->setColor((string) $theme['text'])
        );
        $document->setFooter(
            RunningElement::make((string) $model['footer'] . ' | Page {page} of {pages}')
                ->setAlignment(Alignment::CENTER)
                ->setStyle(
                    TextStyle::make()
                        ->setFontFamily((string) $typography['fontFamily'])
                        ->setFontSize(max(6, (float) $typography['bodySize'] - 1))
                        ->setColor((string) $theme['muted'])
                )
        );

        $section = Section::make($this->sheetName((string) $model['title']));
        $pointsPerMillimeter = 72 / 25.4;
        $margin = (float) $page['pageMargin'] * $pointsPerMillimeter;
        $setup = PageSetup::fromSize(
            $this->pageSize((string) $page['paperSize']),
            (string) $page['orientation']
        )
            ->setPadding($margin, $margin, $margin + 8, $margin)
            ->setBackgroundColor('#FFFFFF');
        $watermarkData = base64_decode((string) ($payload['watermarkData'] ?? ''), true);
        if (is_string($watermarkData) && $watermarkData !== '') {
            $setup
                ->setBackgroundImage(Image::fromData($watermarkData, 'image/jpeg', 600, 400, 'iReserve watermark'))
                ->setBackgroundSize(PageSetup::BG_SIZE_AUTO)
                ->setBackgroundPosition('center center')
                ->setBackgroundRepeat('no-repeat');
        }
        $section->setPageSetup($setup);

        $brandHeaderData = base64_decode((string) ($payload['brandHeaderData'] ?? ''), true);
        if (is_string($brandHeaderData) && $brandHeaderData !== '') {
            $section->addElement(Image::fromData($brandHeaderData, 'image/jpeg', 420, 44, 'iReserve Smart Village Reservation System'));
        }

        $this->addModelParagraph(
            $section,
            (string) $model['title'],
            (string) $typography['fontFamily'],
            (float) $typography['titleSize'],
            (string) $theme['text'],
            true,
            2,
            3
        );
        $filterText = 'Applied Filters: ' . implode(' | ', array_map(
            static fn (array $item): string => (string) $item['label'] . ': ' . (string) $item['value'],
            $model['filters'] ?? []
        ));
        $this->addModelParagraph(
            $section,
            $filterText,
            (string) $typography['fontFamily'],
            max(5.5, (float) $typography['bodySize'] - 1),
            (string) $theme['muted'],
            false,
            0,
            1
        );
        $section->addRule()->setColor((string) $theme['accent'])->setThickness(0.7);
        $section->addElement($this->modelMetadataTable($model));

        if (($model['summary'] ?? []) !== []) {
            $this->addModelParagraph(
                $section,
                'Summary',
                (string) $typography['fontFamily'],
                (float) $typography['sectionSize'],
                (string) $theme['text'],
                true,
                (float) $page['sectionGap'],
                1
            );
            $section->addElement($this->modelSummaryTable($model));
        }

        $this->addModelParagraph(
            $section,
            'Report Details',
            (string) $typography['fontFamily'],
            (float) $typography['sectionSize'],
            (string) $theme['text'],
            true,
            (float) $page['sectionGap'],
            1
        );
        $section->addElement($this->modelDataTable($model));
        $document->addSection($section);

        return $document;
    }

    private function addModelParagraph(
        Section $section,
        string $text,
        string $fontFamily,
        float $fontSize,
        string $color,
        bool $bold,
        float $spaceBefore,
        float $spaceAfter
    ): void {
        $textStyle = TextStyle::make()
            ->setFontFamily($fontFamily)
            ->setFontSize($fontSize)
            ->setColor($color);
        if ($bold) {
            $textStyle->setBold();
        }
        $paragraph = Paragraph::make(
            ParagraphStyle::make()
                ->setSpaceBefore($spaceBefore)
                ->setSpaceAfter($spaceAfter)
                ->setLineSpacing(1.1)
        )->addRun(TextRun::make($text, $textStyle));
        $section->addElement($paragraph);
    }

    /**
     * @param array<string, mixed> $model
     */
    private function modelMetadataTable(array $model): Table
    {
        $theme = $model['theme'];
        $typography = $model['typography'];
        $page = $model['page'];
        $table = Table::make(
            TableStyle::make()
                ->setBorderColor((string) $theme['border'])
                ->setHeaderBg((string) $theme['header'])
                ->setCellPadding((float) $page['cellPadding'])
        )->setColumnWidths([25, 25, 25, 25]);
        $this->addStyledRow(
            $table,
            array_map(static fn (array $item): string => (string) $item['label'], $model['metadata']),
            (string) $typography['fontFamily'],
            (float) $typography['bodySize'],
            true
        );
        $this->addStyledRow(
            $table,
            array_map(static fn (array $item): string => (string) $item['value'], $model['metadata']),
            (string) $typography['fontFamily'],
            (float) $typography['bodySize']
        );

        return $table;
    }

    /**
     * @param array<string, mixed> $model
     */
    private function modelSummaryTable(array $model): Table
    {
        $theme = $model['theme'];
        $typography = $model['typography'];
        $page = $model['page'];
        $table = Table::make(
            TableStyle::make()
                ->setBorderColor((string) $theme['border'])
                ->setHeaderBg((string) $theme['header'])
                ->setCellPadding((float) $page['cellPadding'])
        )->setColumnWidths([65, 35]);
        $this->addStyledRow($table, ['Metric', 'Value'], (string) $typography['fontFamily'], (float) $typography['bodySize'], true);
        foreach ($model['summary'] as $item) {
            $this->addStyledRow(
                $table,
                [(string) $item['label'], (string) $item['value']],
                (string) $typography['fontFamily'],
                (float) $typography['bodySize']
            );
        }

        return $table;
    }

    /**
     * @param array<string, mixed> $model
     */
    private function modelDataTable(array $model): Table
    {
        $theme = $model['theme'];
        $typography = $model['typography'];
        $page = $model['page'];
        $columns = $model['columns'];
        $widths = array_map(static fn (array $column): float => (float) $column['width'], $columns);
        $table = Table::make(
            TableStyle::make()
                ->setBorderColor((string) $theme['border'])
                ->setHeaderBg((string) $theme['header'])
                ->setStripedBg((string) $theme['stripe'])
                ->setCellPadding((float) $page['cellPadding'])
        )->setColumnWidths($widths);
        $this->addStyledRow(
            $table,
            array_map(static fn (array $column): string => (string) $column['label'], $columns),
            (string) $typography['fontFamily'],
            (float) $typography['tableSize'],
            true
        );
        foreach ($model['rows'] as $values) {
            $this->addStyledRow(
                $table,
                array_map(static fn (mixed $value): string => (string) $value, $values),
                (string) $typography['fontFamily'],
                (float) $typography['tableSize']
            );
        }

        return $table;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function metadataTable(array $payload, array $presentation): Table
    {
        $theme = $this->theme($presentation['headerTheme']);
        $table = Table::make(
            TableStyle::make()
                ->setBorderColor($theme['softBorder'])
                ->setHeaderBg($theme['header'])
                ->setCellPadding(5)
        )->setColumnWidths([22, 28, 22, 28]);
        $metadataSize = max(7, (float) $presentation['baseFontSize'] - 4);
        $this->addStyledRow($table, [
            'Generated At',
            $this->dateTime((string) ($payload['generatedAt'] ?? '')),
            'Generated By',
            (string) ($payload['generatedBy'] ?? '-'),
        ], $presentation['fontFamily'], $metadataSize, true);
        $this->addStyledRow($table, [
            'Role',
            $this->label((string) ($payload['generatedByRole'] ?? '-')),
            'Village Scope',
            (string) ($payload['villageScope'] ?? '-'),
        ], $presentation['fontFamily'], $metadataSize);

        return $table;
    }

    /**
     * @param array<int, array<string, mixed>> $summary
     */
    private function summaryTable(array $summary, array $presentation): Table
    {
        $theme = $this->theme($presentation['headerTheme']);
        $table = Table::make(
            TableStyle::make()
                ->setBorderColor($theme['softBorder'])
                ->setHeaderBg($theme['header'])
                ->setStripedBg('#F7FAF8')
                ->setCellPadding($this->cellPadding($presentation['spacing']) + 2)
        );
        $this->addStyledRow($table, ['Metric', 'Value'], $presentation['fontFamily'], max(7, (float) $presentation['baseFontSize'] - 2), true);

        foreach ($summary as $item) {
            $this->addStyledRow($table, [
                (string) ($item['label'] ?? ''),
                $this->formatValue($item['value'] ?? '', (string) ($item['type'] ?? 'text'), true),
            ], $presentation['fontFamily'], max(7, (float) $presentation['baseFontSize'] - 2));
        }

        return $table;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function dataTable(array $payload, bool $displayFormatting): Table
    {
        $columns = $payload['columns'];
        $presentation = $this->presentation($payload);
        $theme = $this->theme($presentation['headerTheme']);
        $isPdf = $displayFormatting;
        $fontSize = $isPdf
            ? max(5.5, min(7.0, (float) $presentation['baseFontSize'] - 4.0))
            : (float) $presentation['baseFontSize'];
        $widths = $this->columnWidths($columns);
        $table = Table::make(
            TableStyle::make()
                ->setBorderColor('#D8E1DD')
                ->setHeaderBg($theme['header'])
                ->setStripedBg('#F4F7F5')
                ->setCellPadding(
                    $isPdf
                        ? max(1.5, $this->cellPadding($presentation['spacing']) - 1.5)
                        : $this->cellPadding($presentation['spacing'])
                )
        )->setColumnWidths($widths);
        $headers = array_map(
            static fn (array $column): string => (string) ($column['label'] ?? $column['key'] ?? ''),
            $columns
        );
        $this->addStyledRow($table, $headers, $presentation['fontFamily'], $fontSize, true);

        foreach ($payload['rows'] as $row) {
            $values = [];
            foreach ($columns as $column) {
                $key = (string) ($column['key'] ?? '');
                $type = (string) ($column['type'] ?? 'text');
                $values[] = $this->formatValue($row[$key] ?? '', $type, $displayFormatting);
            }
            if (! $isPdf) {
                $this->addStyledRow($table, $values, $presentation['fontFamily'], $fontSize);
                continue;
            }

            $this->addStyledRow($table, $values, $presentation['fontFamily'], $fontSize);
        }

        return $table;
    }

    /**
     * @param array<int, string> $values
     */
    private function addStyledRow(
        Table $table,
        array $values,
        string $fontFamily,
        float $fontSize,
        bool $isHeader = false
    ): void {
        $row = TableRow::make()->setHeader($isHeader);
        foreach ($values as $value) {
            $style = TextStyle::make()
                ->setFontFamily($fontFamily)
                ->setFontSize($fontSize)
                ->setColor('#17211D');
            if ($isHeader) {
                $style->setBold();
            }
            $row->addCell(
                TableCell::make()->addElement(
                    Paragraph::make()->addRun(TextRun::make((string) $value, $style))
                )
            );
        }
        $table->addRow($row);
    }

    /**
     * @param array<int, array<string, mixed>> $columns
     * @return array<int, float>
     */
    private function columnWidths(array $columns): array
    {
        $widths = [];
        foreach ($columns as $column) {
            $key = strtolower((string) ($column['key'] ?? ''));
            $label = strtolower((string) ($column['label'] ?? ''));
            $type = (string) ($column['type'] ?? 'text');
            $weight = 1.0;
            if (str_contains($key, 'description') || str_contains($key, 'message') || str_contains($key, 'rejectionreason')) {
                $weight = 2.0;
            } elseif (
                str_contains($key, 'customer')
                || str_contains($key, 'village')
                || str_contains($key, 'property')
                || str_contains($key, 'reference')
            ) {
                $weight = 1.45;
            } elseif ($type === 'currency') {
                $weight = 1.3;
            } elseif ($type === 'datetime') {
                $weight = 1.35;
            } elseif ($type === 'date' || str_contains($key, 'status') || str_contains($label, 'status')) {
                $weight = 1.15;
            } elseif ($type === 'number') {
                $weight = 0.85;
            }
            $widths[] = $weight;
        }

        return $widths;
    }

    /**
     * @param array<string, mixed> $filters
     */
    private function filtersText(array $filters): string
    {
        if ($filters === []) {
            return 'No filters applied.';
        }

        $parts = [];
        foreach ($filters as $key => $value) {
            if ($value === '' || $value === null || $key === 'datePreset') {
                continue;
            }
            $parts[] = $this->filterLabel((string) $key) . ': ' . $this->filterValue((string) $key, (string) $value);
        }

        return $parts === [] ? 'No filters applied.' : implode(' | ', $parts);
    }

    private function filterLabel(string $key): string
    {
        $known = [
            'villageId' => 'Village',
            'propertyId' => 'Property',
            'customerId' => 'Customer',
            'sortBy' => 'Sort By',
        ];
        if (isset($known[$key])) {
            return $known[$key];
        }
        $spaced = preg_replace('/(?<!^)[A-Z]/', ' $0', $key);
        return ucwords(str_replace('_', ' ', (string) $spaced));
    }

    private function filterValue(string $key, string $value): string
    {
        if (in_array($key, ['dateFrom', 'dateTo'], true)) {
            return $value;
        }

        return $this->label($value);
    }

    private function formatValue(mixed $value, string $type, bool $displayFormatting): string
    {
        if ($value === null || $value === '') {
            return '-';
        }
        if (! $displayFormatting) {
            return is_bool($value) ? ($value ? 'Yes' : 'No') : (string) $value;
        }

        return match ($type) {
            'currency' => 'PHP ' . number_format((float) $value, 2, '.', ','),
            'number' => number_format((float) $value, 0, '.', ','),
            'date' => $this->date((string) $value),
            'datetime' => $this->dateTime((string) $value),
            default => $this->label((string) $value),
        };
    }

    private function date(string $value): string
    {
        $timestamp = strtotime($value);
        return $timestamp ? date('M j, Y', $timestamp) : $value;
    }

    private function dateTime(string $value): string
    {
        $timestamp = strtotime($value);
        return $timestamp ? date('M j, Y g:i A', $timestamp) : ($value ?: '-');
    }

    private function label(string $value): string
    {
        return ucwords(str_replace(['_', '-'], ' ', $value));
    }

    private function sheetName(string $title): string
    {
        $clean = preg_replace('/[\\\\\/\?\*\[\]:]+/', ' ', $title);
        return substr(trim((string) $clean), 0, 31) ?: 'Report';
    }

    /**
     * @param array<string, mixed> $payload
     * @return array{fontFamily: string, baseFontSize: string, paperSize: string, orientation: string, spacing: string, headerTheme: string}
     */
    private function presentation(array $payload): array
    {
        return array_merge([
            'fontFamily' => 'Arial',
            'baseFontSize' => '11',
            'paperSize' => 'a4',
            'orientation' => 'portrait',
            'spacing' => 'balanced',
            'headerTheme' => 'property_accent',
        ], is_array($payload['presentation'] ?? null) ? $payload['presentation'] : []);
    }

    private function pageSize(string $size): PageSize
    {
        return match ($size) {
            'letter' => PageSize::LETTER,
            'legal' => PageSize::LEGAL,
            default => PageSize::A4,
        };
    }

    /**
     * @return array{accent: string, header: string, soft: string, softBorder: string}
     */
    private function theme(string $name): array
    {
        return match ($name) {
            'fresh_lime' => ['accent' => '#527D16', 'header' => '#D4FF8A', 'soft' => '#F4FFE1', 'softBorder' => '#B9DF75'],
            'emerald' => ['accent' => '#047857', 'header' => '#A7F3D0', 'soft' => '#ECFDF5', 'softBorder' => '#6EE7B7'],
            'teal' => ['accent' => '#0F766E', 'header' => '#99F6E4', 'soft' => '#ECFDFB', 'softBorder' => '#5EEAD4'],
            'sage' => ['accent' => '#52725A', 'header' => '#CFE3C9', 'soft' => '#F1F7EF', 'softBorder' => '#ADC9A5'],
            'navy' => ['accent' => '#1E3A5F', 'header' => '#BFDBFE', 'soft' => '#EEF3F8', 'softBorder' => '#93C5FD'],
            'slate' => ['accent' => '#475569', 'header' => '#CBD5E1', 'soft' => '#F1F5F9', 'softBorder' => '#94A3B8'],
            default => ['accent' => '#16835F', 'header' => '#BFE8D8', 'soft' => '#EDF6F2', 'softBorder' => '#8ECBB5'],
        };
    }

    private function cellPadding(string $spacing): float
    {
        return match ($spacing) {
            'compact' => 2.5,
            'comfortable' => 6.0,
            default => 4.0,
        };
    }
}
